# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


management:
    profiles:
        active: dev
        include: swagger
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: microservices

    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false


security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true


# ===================================================================
# Erx specific properties

# ===================================================================

erx:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800

    swagger:
        basePackage: com.erx.microservice.patientmanagement.web.rest
        default-include-pattern: /api/.*
        title: PatientManagement API
        description: PatientManagement API documentation
        version: 1.0.0
        terms-of-service-url: http://www.erxsolutions.in/
        contact-name: eRx Tech Team
        contact-url: http://www.erxsolutions.in/
        contact-email: patil.mk@erxindia.in
        license: http://www.erxsolutions.in/
        license-url: http://www.erxsolutions.in/

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the ErxProperties above

# ===================================================================

application:
    message: default

