# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: dev
        include: swagger

    application:
        name: Dev-Patient-Management-Service

    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://122.166.179.22:3306/erx3?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: erx
        password: a1b2c3
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1

logging:
    level:
        com.erx.microservice: DEBUG

server:
    port: 9091

# ===================================================================
# Erx specific properties
#
# ===================================================================

erx:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: jhipsterapp@localhost
        base-url: http://127.0.0.1:8080
    microservices-references: # specific JHipster mail property, for standard properties see MailProperties
        utility-service: http://localhost:12011
        billing-service: http://localhost:11011
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics: # Reports Spectator Circuit Breaker metrics in the logs
            enabled: false
            # edit spring.metrics.export.delay-millis to set report frequency
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the ErxProperties above
#

# ===================================================================

application:
    message: default-dev
